version: '3'
services:
  workspace:
    build:
      context: ./docker/workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - .:/var/www:cached
    tty: true
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - phpsocket:/var/run
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - workspace
      - php-fpm
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - .:/var/www:cached
      - ./docker/php-fpm/usr/local/etc/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpsocket:/var/run
    tty: true
    depends_on:
      - workspace
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/etc/mysql/conf.d/zz-docker.cnf:/etc/mysql/conf.d/zz-docker.cnf
      - mysql:/var/lib/mysql:cached
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis

volumes:
  mysql:
    driver: local
  phpsocket:
    driver: local
